-- sas_it_order
CREATE TABLE IF NOT EXISTS adempiere.sas_it_order (
    sas_it_order_id NUMERIC(10,0) NOT NULL,
    ad_client_id NUMERIC(10,0) NOT NULL,
    ad_org_id NUMERIC(10,0) NOT NULL,
    ad_orgtrx_id NUMERIC(10,0),
    isactive CHARACTER(1) NOT NULL DEFAULT 'Y'::bpchar,
    created NOT NULL TIMESTAMP WITHOUT TIME ZONE,
    createdby NUMERIC(10,0) NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updatedby NUMERIC(10,0) NOT NULL,
    issotrx CHARACTER(1) NOT NULL,
    documentno CHARACTER VARYING(30) NOT NULL,
    docstatus CHARACTER(2) NOT NULL,
    orderstatus CHARACTER(2) NOT NULL,
    c_doctypetarget_id NUMERIC(10,0) NOT NULL,
    dateordered TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    c_bpartner_id NUMERIC(10,0) NOT NULL,
    c_bpartner_location_id NUMERIC(10,0) NOT NULL,
    bill_bpartner_id NUMERIC(10,0),
    bill_location_id NUMERIC(10,0),
    invoicerule CHARACTER(1) NOT NULL,
    priorityrule CHARACTER(1) NOT NULL,
    m_warehouse_id NUMERIC(10,0) NOT NULL,
    isshipment CHARACTER(1) NOT NULL DEFAULT 'N'::bpchar,
    countgnrt NUMERIC(10,0) NOT NULL DEFAULT '0'::numeric,
    isemail CHARACTER(1) NOT NULL DEFAULT 'N'::bpchar,
    picklistnote CHARACTER VARYING(255) DEFAULT NULL::character varying,
    shipmentnote CHARACTER VARYING(255) DEFAULT NULL::character varying,
    invoicenote CHARACTER VARYING(255) DEFAULT NULL::character varying,
)